name: Setup Alpine Linux
description: Setup Alpine Linux (WIP)
inputs:
  arch:
    description: >
      CPU architecture to emulate using QEMU. Allowed values are: `x86_64` (native), `x86`,
      `aarch64`, `armhf` (armv6 with hard-float), `armv7`, `ppc64le`, `riscv64` (available only
      for branch `edge`), and `s390x`
    required: false
    default: x86_64
  branch:
    description: Alpine branch (aka release) to install (e.g. `v3.15`, `latest-stable`, `edge`).
    required: false
    default: latest-stable
  extra-repositories:
    description: >
      Additional Alpine repositories to add into /etc/apk/repositories (Alpine's official main and
      community repositories are always added).
    required: false
    default: ''
  packages:
    description: Alpine packages to install.
    required: false
    default: ''
  shell-name:
    description: >
      Name of the script to run `sh` in the Alpine chroot that will be added to `GITHUB_PATH`.
      This name should be used in `jobs.<job_id>.steps[*].shell` (e.g. `shell: alpine.sh {0}`) to
      run the step's script in the chroot.
    required: false
    default: alpine-sh
outputs:
  root-path:
    description: >
      Path to the created Alpine root directory (also exposed in environment
      variable ALPINE_ROOT_PATH).
    value: ${{ steps.install.outputs.root-path }}

runs:
  using: composite
  steps:
    # TODO: Replace alpine-chroot-install with a derivate (re)written specifically
    #  for setup-alpine and stored in this repository.
    - run: |
        wget -T 10 --no-verbose https://raw.githubusercontent.com/alpinelinux/alpine-chroot-install/v0.13.3/alpine-chroot-install
        echo 'c3005e323029637db20ec9595243ac94bb9b2226  alpine-chroot-install' | sha1sum -c
        chmod +x alpine-chroot-install
        # TODO: Remove after update to v0.13.4
        sed -i 's/apt-get install /&-o=Dpkg::Use-Pty=0 /' alpine-chroot-install
      shell: bash

    - id: install
      run: |
        ROOT_PATH="$HOME/rootfs/alpine-${{ inputs.branch }}-${{ inputs.arch }}"
        sudo ./alpine-chroot-install \
          -a "${{ inputs.arch }}" \
          -b "${{ inputs.branch }}" \
          -r "${{ inputs.extra-repositories }}" \
          -p "${{ inputs.packages }}" \
          -k ".*" \
          -i "/home/runner/work" \
          -d "$ROOT_PATH"
        rm alpine-chroot-install
        echo "::set-output name=root-path::$ROOT_PATH"
      shell: bash

    - run: |
        arch=${{ inputs.arch }}

        sudo install -D -m755 /dev/stdin "$ROOT_PATH/xbin/${{ inputs.shell-name }}" <<EOF
        #!/bin/sh
        case "\$1" in
            -r | --root) USER=root; shift;;
        esac
        exec "$ROOT_PATH"/enter-chroot -u \$USER sh -eo pipefail "\$@"
        EOF

        echo "$ROOT_PATH/xbin" >> $GITHUB_PATH
      env:
        ROOT_PATH: ${{ steps.install.outputs.root-path }}
      shell: bash

    - uses: webiny/action-post-run@2.0.1
      with:
        run: ${{ steps.install.outputs.root-path }}/destroy --remove
